import { UID_PREFIX_JEST_INTEGRATION_HOOK } from "../../hook/constants/UID_PREFIX_JEST_INTEGRATION_HOOK";

export const JEST_INTEGRATION_HOOK_UID_GENERATE_CONFIG_ASYNC = `${UID_PREFIX_JEST_INTEGRATION_HOOK}generateConfigAsync`;
