import { TYPESCRIPT_LINTER_CONFIG_NAME_PREFIX } from "../../constants/TYPESCRIPT_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_TYPESCRIPT_CJS_CTS_JS_MJS_MTS_TS = `${TYPESCRIPT_LINTER_CONFIG_NAME_PREFIX}cjs-cts-js-mjs-mts-ts`;
