import { ESLINT_MARKDOWN_LINTER_CONFIG_NAME_PREFIX } from "../../constants/ESLINT_MARKDOWN_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_PREFIX_ESLINT_MARKDOWN_RECOMMENDED = `${ESLINT_MARKDOWN_LINTER_CONFIG_NAME_PREFIX}recommended`;
