import { CSPELL_LINTER_CONFIG_NAME_PREFIX } from "./constants/CSPELL_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_CSPELL_RECOMMENDED = `${CSPELL_LINTER_CONFIG_NAME_PREFIX}recommended`;
