import { UID_PREFIX_BABEL_INTEGRATION_HOOK } from "../../hook/constants/UID_PREFIX_BABEL_INTEGRATION_HOOK";

export const BABEL_INTEGRATION_HOOK_UID_GENERATE_TRANSFORM_OPTIONS_SYNC = `${UID_PREFIX_BABEL_INTEGRATION_HOOK}generateTransformOptionsSync`;
