version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Istanbul"
    groups:
      babel:
        patterns:
          - "@babel/*"
          - "@types/babel__*"
          - "babel-*"
      eslint:
        patterns:
          - "@cspell/*"
          - "@eslint/*"
          - "@types/node"
          - "@types/picomatch"
          - "eslint"
          - "eslint-*"
          - "*-eslint"
          - "*/eslint-*"
          - "globals"
