import { UID_PREFIX_WEBPACK_INTEGRATION_HOOK } from "../../hook/constants/UID_PREFIX_WEBPACK_INTEGRATION_HOOK";

export const WEBPACK_INTEGRATION_HOOK_UID_GENERATE_CONFIGURATION_ASYNC = `${UID_PREFIX_WEBPACK_INTEGRATION_HOOK}generateConfigurationAsync`;
