enableGlobalCache: false
enableTelemetry: false
injectEnvironmentFiles:
  - .env.yarn?
  - .env?
  - .env.local?
nmHoistingLimits: none
nmMode: classic
nodeLinker: node-modules
tsEnableAutoTypes: true
