import { UID_PREFIX_ESLINT_INTEGRATION_HOOK } from "../../hook/constants/UID_PREFIX_ESLINT_INTEGRATION_HOOK";

export const ESLINT_INTEGRATION_HOOK_UID_GENERATE_LINTER_CONFIG_ARRAY_SYNC = `${UID_PREFIX_ESLINT_INTEGRATION_HOOK}generateLinterConfigArraySync`;
