import { TYPESCRIPT_LINTER_CONFIG_NAME_PREFIX } from "../../constants/TYPESCRIPT_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_PREFIX_TYPESCRIPT_STRICT_TYPE_CHECKED = `${TYPESCRIPT_LINTER_CONFIG_NAME_PREFIX}strict-type-checked`;
