import { JSDOC_LINTER_CONFIG_NAME_PREFIX } from "../../constants/JSDOC_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_JSDOC_CTS_CTSX_MTS_MTSX_TS_TSX = `${JSDOC_LINTER_CONFIG_NAME_PREFIX}cts-ctsx-mts-mtsx-ts-tsx`;
