import { IMPORT_X_LINTER_CONFIG_NAME_PREFIX } from "../../constants/IMPORT_X_LINTER_CONFIG_NAME_PREFIX";
export const LINTER_CONFIG_NAME_IMPORT_X_CUSTOM = `${IMPORT_X_LINTER_CONFIG_NAME_PREFIX}custom`;
