import { UID_PREFIX_FIRST_PARTY_INTEGRATION } from "@holypack/core/integration/constants/UID_PREFIX_FIRST_PARTY_INTEGRATION";

export const INTEGRATION_UID_ESLINT_PLUGIN_IMPORT_X = `${UID_PREFIX_FIRST_PARTY_INTEGRATION}eslint/plugins/import-x`;
