import { STYLISTIC_LINTER_CONFIG_NAME_PREFIX } from "../../constants/STYLISTIC_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_STYLISTIC_CUSTOMIZED_CJSX_CTSX_JSX_MJSX_MTSX_TSX = `${STYLISTIC_LINTER_CONFIG_NAME_PREFIX}customized-cjsx-ctsx-jsx-mjsx-mtsx-tsx`;
