import { ESLINT_JS_LINTER_CONFIG_NAME_PREFIX } from "../../constants/ESLINT_JS_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_ESLINT_JS_CUSTOM = `${ESLINT_JS_LINTER_CONFIG_NAME_PREFIX}custom`;
