import { PERFECTIONIST_LINTER_CONFIG_NAME_PREFIX } from "../../constants/PERFECTIONIST_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_PERFECTIONIST_CUSTOM = `${PERFECTIONIST_LINTER_CONFIG_NAME_PREFIX}custom`;
