import { GLOBALS_LINTER_CONFIG_NAME_PREFIX } from "../../constants/GLOBALS_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_GLOBALS_JS_JSX_TS_TSX = `${GLOBALS_LINTER_CONFIG_NAME_PREFIX}js-jsx-ts-tsx`;
