import { JEST_LINTER_CONFIG_NAME_PREFIX } from "../../constants/JEST_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_ISTANBUL_RECOMMENDED = `${JEST_LINTER_CONFIG_NAME_PREFIX}istanbul/recommended`;
