import { GLOBALS_LINTER_CONFIG_NAME_PREFIX } from "../../constants/GLOBALS_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_GLOBALS_CJS_CJSX_CTS_CTSX = `${GLOBALS_LINTER_CONFIG_NAME_PREFIX}cjs-cjsx-cts-ctsx`;
