import { IMPORT_X_LINTER_CONFIG_NAME_PREFIX } from "../../constants/IMPORT_X_LINTER_CONFIG_NAME_PREFIX";
export const LINTER_CONFIG_NAME_IMPORT_X_RECOMMENDED = `${IMPORT_X_LINTER_CONFIG_NAME_PREFIX}recommended`;
