import { UID_PREFIX_FIRST_PARTY_INTEGRATION } from "@holypack/core/integration/constants/UID_PREFIX_FIRST_PARTY_INTEGRATION";

export const INTEGRATION_UID_ESLINT = `${UID_PREFIX_FIRST_PARTY_INTEGRATION}eslint`;
