import { TYPESCRIPT_LINTER_CONFIG_NAME_PREFIX } from "../../constants/TYPESCRIPT_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_TYPESCRIPT_CUSTOM = `${TYPESCRIPT_LINTER_CONFIG_NAME_PREFIX}custom`;
