import { ESLINT_MARKDOWN_LINTER_CONFIG_NAME_PREFIX } from "../../constants/ESLINT_MARKDOWN_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_ESLINT_MARKDOWN_GFM_LABEL_REFS_FIX = `${ESLINT_MARKDOWN_LINTER_CONFIG_NAME_PREFIX}gfm-label-refs-fix`;
