export { createBabelIntegrationPluginImportSourceTransformer } from "./extension/createBabelIntegrationPluginImportSourceTransformer";
import { createBabelIntegrationPluginImportSourceTransformer } from "./extension/createBabelIntegrationPluginImportSourceTransformer";

export default createBabelIntegrationPluginImportSourceTransformer;
