import { dirname } from "node:path";

import { EXTENSION_TESTS_CONSTANTS_DIRECTORY_PATH } from "./EXTENSION_TESTS_CONSTANTS_DIRECTORY_PATH";

export const EXTENSION_TESTS_DIRECTORY_PATH = dirname(
  EXTENSION_TESTS_CONSTANTS_DIRECTORY_PATH,
);
