import { TYPESCRIPT_LINTER_CONFIG_NAME_PREFIX } from "../../constants/TYPESCRIPT_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_TYPESCRIPT_CJSX_CTSX_JSX_MJSX_MTSX_TSX = `${TYPESCRIPT_LINTER_CONFIG_NAME_PREFIX}cjsx-ctsx-jsx-mjsx-mtsx-tsx`;
