import { GLOBALS_LINTER_CONFIG_NAME_PREFIX } from "../../constants/GLOBALS_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_GLOBALS_MJS_MJSX_MTS_MTSX = `${GLOBALS_LINTER_CONFIG_NAME_PREFIX}mjs-mjsx-mts-mtsx`;
