import { UID_PREFIX_FIRST_PARTY_INTEGRATION } from "@holypack/core/integration/constants/UID_PREFIX_FIRST_PARTY_INTEGRATION";

export const INTEGRATION_UID_ESLINT_PLUGIN_CSPELL = `${UID_PREFIX_FIRST_PARTY_INTEGRATION}eslint/plugins/cspell`;
