import { JSDOC_LINTER_CONFIG_NAME_PREFIX } from "../../constants/JSDOC_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_JSDOC_RECOMMENDED_JAVASCRIPT = `${JSDOC_LINTER_CONFIG_NAME_PREFIX}recommended-javascript`;
