import { STYLISTIC_LINTER_CONFIG_NAME_PREFIX } from "../../constants/STYLISTIC_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_STYLISTIC_CUSTOMIZED_CJS_CTS_JS_MJS_MTS_TS = `${STYLISTIC_LINTER_CONFIG_NAME_PREFIX}customized-cjs-cts-js-mjs-mts-ts`;
