import { STYLISTIC_LINTER_CONFIG_NAME_PREFIX } from "../../constants/STYLISTIC_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_STYLISTIC_RECOMMENDED = `${STYLISTIC_LINTER_CONFIG_NAME_PREFIX}recommended`;
