import type { ESLintIntegrationPluginPerfectionistResolvedOptionInternalPattern } from "./internal-pattern/ESLintIntegrationPluginPerfectionistResolvedOptionInternalPattern";

export type ESLintIntegrationPluginPerfectionistResolvedOptions = {
  internalPattern: ESLintIntegrationPluginPerfectionistResolvedOptionInternalPattern;
};
