import { YML_LINTER_CONFIG_NAME_PREFIX } from "../../constants/YML_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_PREFIX_YML_RECOMMENDED = `${YML_LINTER_CONFIG_NAME_PREFIX}recommended`;
