import { ESLINT_JSON_LINTER_CONFIG_NAME_PREFIX } from "../../constants/ESLINT_JSON_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_ESLINT_JSON_JSONC = `${ESLINT_JSON_LINTER_CONFIG_NAME_PREFIX}jsonc`;
