import { TYPESCRIPT_LINTER_CONFIG_NAME_PREFIX } from "../../constants/TYPESCRIPT_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_TYPESCRIPT_CJS_CJSX_CTS_CTSX = `${TYPESCRIPT_LINTER_CONFIG_NAME_PREFIX}cjs-cjsx-cts-ctsx`;
