import { PERFECTIONIST_LINTER_CONFIG_NAME_PREFIX } from "../../constants/PERFECTIONIST_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_PERFECTIONIST_RECOMMENDED_NATURAL = `${PERFECTIONIST_LINTER_CONFIG_NAME_PREFIX}recommended-natural`;
