import { ESLINT_GLOBAL_IGNORES_LINTER_CONFIG_NAME_PREFIX } from "../../constants/ESLINT_GLOBAL_IGNORES_LINTER_CONFIG_NAME_PREFIX";

export const LINTER_CONFIG_NAME_ESLINT_GLOBAL_IGNORES_CUSTOM = `${ESLINT_GLOBAL_IGNORES_LINTER_CONFIG_NAME_PREFIX}custom`;
