import { UID_PREFIX_PROCESS_WARNING_MONITOR_HOOK } from "../../hook/constants/UID_PREFIX_PROCESS_WARNING_MONITOR_HOOK";

export const PROCESS_WARNING_MONITOR_HOOK_UID_EMIT_WARNING_SYNC = `${UID_PREFIX_PROCESS_WARNING_MONITOR_HOOK}emitWarningSync`;
