name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/ci-setup

  lint:
    if: ${{ needs.build.result == 'success' }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/ci-setup
      - name: Lint
        run: yarn eslint:lint

  test:
    if: ${{ needs.build.result == 'success' }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/ci-setup
      - name: Test
        run: yarn test

  build-e2e:
    if: ${{ needs.build.result == 'success' && needs.test.result == 'success' }}
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/ci-setup
      - name: Setup E2E
        uses: ./.github/actions/ci-setup-e2e

  test-e2e:
    if: ${{ needs.build-e2e.result == 'success' }}
    runs-on: ubuntu-latest
    needs: [build-e2e]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/ci-setup
      - name: Setup E2E
        uses: ./.github/actions/ci-setup-e2e
      - name: Test E2E
        run: yarn e2e:test
